# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
# #
# commands:
#   print_pipeline_id:
#     description: "A very simple command for demonstration purposes"
#     parameters:
#       to:
#         type: string
#         default: "-1"
#     steps:
#       - run: echo << parameters.to >>
# jobs:
#   hello_world_output:
#     docker:
#       - image: circleci/node:13.8.0 
#     steps:
#       - print_pipeline_id: 
#           to :  ${CIRCLE_WORKFLOW_ID}
jobs:    
  build:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: npm i
      - run: npm run lint

  test:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: 
          npm run test
  analyze:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: 
          npm audit

workflows:
  Test-failure:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test    
